language: go

go: "1.13"

before_install:
  - ./scripts/check_release_exists.sh

after_success:
  - go build -o output/service
  - ./scripts/publish_docker_build.sh

addons:
  apt:
    update: true

services:
  - docker